
+define+DEBUG

-suppress 2167

-sv 

+incdir+../../
+libext+.mif

../../rtl/cpu32e2/rtl/globals.sv
../../rtl/cpu32e2/rtl/boolPkg.sv
../../rtl/cpu32e2/rtl/execute/alu/rtl/aluPkg.sv
../../rtl/cpu32e2/rtl/execute/alu/rtl/alu.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/divider2Pkg.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/dividendState.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/divisorState.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/remainderState.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/divider2Controller.sv
../../rtl/cpu32e2/rtl/execute/divider2/rtl/divider2.sv
../../rtl/cpu32e2/rtl/execute/multiplier/rtl/dspMultiplier.v
../../rtl/cpu32e2/rtl/execute/multiplier/rtl/multiplier.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shifterPkg.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shift1.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shift2.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shift4.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shift8.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shift16.sv
../../rtl/cpu32e2/rtl/execute/shifter/rtl/shifter.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfileMemoryBlock2.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfileBank.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfileInputRegisters.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfileLiveValueTable.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfile.sv
../../rtl/cpu32e2/rtl/regfile/rtl/regfileDebug.sv
../../rtl/cpu32e2/rtl/architecture.sv
../../rtl/cpu32e2/rtl/debugPkg.sv
../../rtl/cpu32e2/rtl/address.sv
../../rtl/cpu32e2/rtl/data.sv
../../rtl/cpu32e2/rtl/exceptionEncoder.sv
../../rtl/cpu32e2/rtl/exceptionState.sv
../../rtl/cpu32e2/rtl/exception.sv
../../rtl/cpu32e2/rtl/exceptionTrigger.sv
../../rtl/cpu32e2/rtl/execute.sv
../../rtl/cpu32e2/rtl/load.sv
../../rtl/cpu32e2/rtl/programCounter.sv
../../rtl/cpu32e2/rtl/registerFile.sv
../../rtl/cpu32e2/rtl/result.sv
../../rtl/cpu32e2/rtl/system.sv
../../rtl/cpu32e2/rtl/transaction.sv
../../rtl/cpu32e2/rtl/controller/controllerPkg.sv
../../rtl/cpu32e2/rtl/controller/controllerState.sv
../../rtl/cpu32e2/rtl/controller/addressOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/conditionCheckLogic.sv
../../rtl/cpu32e2/rtl/controller/dataOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/exceptionOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/exceptionTriggerOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/executeOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/instructionDecoder.sv
../../rtl/cpu32e2/rtl/controller/loadOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/programCounterOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/regfileAOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/regfileBOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/resultFlagsOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/resultOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/stallLogic.sv
../../rtl/cpu32e2/rtl/controller/systemOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/transactionOutputLogic.sv
../../rtl/cpu32e2/rtl/controller/controller.sv
../../rtl/cpu32e2/rtl/cpu32e2.sv

../../rtl/dataSelect/dataSelect.sv
../../rtl/io/io.sv
../../rtl/pll/pll.v
../../rtl/pll/pll2.v
../../rtl/ram/ram.sv
../../rtl/ram/systemRam.v
../../rtl/resetCore/resetCore.sv
../../rtl/resetCore/resetMasterSync.sv
../../rtl/resetCore/resetSync.sv
../../rtl/uart/rtl/uart.sv
../../rtl/uart/rtl/uartCore.sv
../../rtl/uart/rtl/uartReceiver.sv
../../rtl/uart/rtl/uartTransmitter.sv
../../rtl/random/randomCore.sv
../../rtl/random/random.sv
../../rtl/timer/timerUnit.sv
../../rtl/timer/timerCore.sv
../../rtl/timer/timer.sv
../../rtl/sdram/soc32e_sdram.v
../../rtl/sdram/sdram.sv
../../rtl/adc/adc.sv
../../rtl/adc/altera_modular_adc_control.v
../../rtl/adc/altera_modular_adc_control_avrg_fifo.v
../../rtl/adc/altera_modular_adc_control_fsm.v
../../rtl/adc/altera_modular_adc_sample_store.v
../../rtl/adc/altera_modular_adc_sample_store_ram.v
../../rtl/adc/altera_modular_adc_sequencer.v
../../rtl/adc/altera_modular_adc_sequencer_csr.v
../../rtl/adc/altera_modular_adc_sequencer_ctrl.v
../../rtl/adc/chsel_code_converter_sw_to_hw.v
../../rtl/adc/fiftyfivenm_adcblock_top_wrapper.v
../../rtl/adc/fiftyfivenm_adcblock_primitive_wrapper.v
../../rtl/adc/soc32e_modular_adc_0.v
../../rtl/spi/rtl/spi.sv
../../rtl/spi/rtl/spiCore.sv
../../rtl/spi/rtl/spiUnit.sv
../../rtl/sound/rtl/buffer.sv
../../rtl/sound/rtl/bufferMemory.sv
../../rtl/sound/rtl/pwmUnit.sv
../../rtl/sound/rtl/sigmaDeltaUnit.sv
../../rtl/sound/rtl/sound.sv
../../rtl/sound/rtl/soundCore.sv

../../rtl/interrupt/interruptController.sv
../../rtl/interrupt/interruptState.sv
../../rtl/addressMap/addressMap.sv

../../rtl/soc32e.sv
soc32e_tb.sv

