
+define+DEBUG

-suppress 2167

-sv 

+incdir+../../../
+libext+.mif

../../../parts/cpu32e2/rtl/globals.sv
../../../parts/cpu32e2/rtl/boolPkg.sv
../../../parts/cpu32e2/rtl/execute/alu/rtl/aluPkg.sv
../../../parts/cpu32e2/rtl/execute/alu/rtl/alu.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/divider2Pkg.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/dividendState.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/divisorState.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/remainderState.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/divider2Controller.sv
../../../parts/cpu32e2/rtl/execute/divider2/rtl/divider2.sv
../../../parts/cpu32e2/rtl/execute/multiplier/rtl/dspMultiplier.v
../../../parts/cpu32e2/rtl/execute/multiplier/rtl/multiplier.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shifterPkg.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shift1.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shift2.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shift4.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shift8.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shift16.sv
../../../parts/cpu32e2/rtl/execute/shifter/rtl/shifter.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfileMemoryBlock2.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfileBank.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfileInputRegisters.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfileLiveValueTable.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfile.sv
../../../parts/cpu32e2/rtl/regfile/rtl/regfileDebug.sv
../../../parts/cpu32e2/rtl/architecture.sv
../../../parts/cpu32e2/rtl/debugPkg.sv
../../../parts/cpu32e2/rtl/address.sv
../../../parts/cpu32e2/rtl/data.sv
../../../parts/cpu32e2/rtl/exceptionEncoder.sv
../../../parts/cpu32e2/rtl/exceptionState.sv
../../../parts/cpu32e2/rtl/exception.sv
../../../parts/cpu32e2/rtl/exceptionTrigger.sv
../../../parts/cpu32e2/rtl/execute.sv
../../../parts/cpu32e2/rtl/load.sv
../../../parts/cpu32e2/rtl/programCounter.sv
../../../parts/cpu32e2/rtl/registerFile.sv
../../../parts/cpu32e2/rtl/result.sv
../../../parts/cpu32e2/rtl/system.sv
../../../parts/cpu32e2/rtl/transaction.sv
../../../parts/cpu32e2/rtl/controller/controllerPkg.sv
../../../parts/cpu32e2/rtl/controller/controllerState.sv
../../../parts/cpu32e2/rtl/controller/addressOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/conditionCheckLogic.sv
../../../parts/cpu32e2/rtl/controller/dataOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/exceptionOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/exceptionTriggerOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/executeOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/instructionDecoder.sv
../../../parts/cpu32e2/rtl/controller/loadOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/programCounterOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/regfileAOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/regfileBOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/resultFlagsOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/resultOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/stallLogic.sv
../../../parts/cpu32e2/rtl/controller/systemOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/transactionOutputLogic.sv
../../../parts/cpu32e2/rtl/controller/controller.sv
../../../parts/cpu32e2/rtl/cpu32e2.sv

../../../parts/io/rtl/io.sv
../../../parts/pll/rtl/pll.v
../../../parts/pll/rtl/pll2.v
../../../parts/ram/rtl/ram.sv
../../../parts/ram/rtl/systemRam.v
../../../parts/resetCore/rtl/resetCore.sv
../../../parts/resetCore/rtl/resetMasterSync.sv
../../../parts/resetCore/rtl/resetSync.sv
../../../parts/uart/rtl/uart.sv
../../../parts/uart/rtl/uartCore.sv
../../../parts/uart/rtl/uartReceiver.sv
../../../parts/uart/rtl/uartTransmitter.sv
../../../parts/uart/rtl/uart2.sv
../../../parts/uart/rtl/uartCore2.sv
../../../parts/uart/rtl/uartFifoMemory.sv
../../../parts/uart/rtl/uartFifo.sv
../../../parts/uart/rtl/uartReceiver2.sv
../../../parts/vga/rtl/lineBuffer.sv
//../../../parts/vga/rtl/lineFetchController.sv
//../../../parts/vga/rtl/sdramArbiterFifoMemory.sv
//../../../parts/vga/rtl/sdramArbiterFifo.sv
//../../../parts/vga/rtl/sdramArbiter.sv
../../../parts/vga/rtl/vgaDriver.sv
../../../parts/vga/rtl/vgaCore.sv
//../../../parts/vga/rtl/vga.sv
../../../parts/i2c/rtl/i2cClockUnit.sv
../../../parts/i2c/rtl/i2cUnit.sv
../../../parts/i2c/rtl/i2cCore.sv
../../../parts/i2c/rtl/i2c.sv
../../../parts/random/rtl/randomCore.sv
../../../parts/random/rtl/random.sv
../../../parts/timer/rtl/timerUnit.sv
../../../parts/timer/rtl/timerCore.sv
../../../parts/timer/rtl/timer.sv
../../../parts/sdram/rtl/soc32e_sdram.v
../../../parts/sdram/rtl/sdram.sv
../../../parts/adc/rtl/adc.sv
../../../parts/adc/rtl/altera_modular_adc_control.v
../../../parts/adc/rtl/altera_modular_adc_control_avrg_fifo.v
../../../parts/adc/rtl/altera_modular_adc_control_fsm.v
../../../parts/adc/rtl/altera_modular_adc_sample_store.v
../../../parts/adc/rtl/altera_modular_adc_sample_store_ram.v
../../../parts/adc/rtl/altera_modular_adc_sequencer.v
../../../parts/adc/rtl/altera_modular_adc_sequencer_csr.v
../../../parts/adc/rtl/altera_modular_adc_sequencer_ctrl.v
../../../parts/adc/rtl/chsel_code_converter_sw_to_hw.v
../../../parts/adc/rtl/fiftyfivenm_adcblock_top_wrapper.v
../../../parts/adc/rtl/fiftyfivenm_adcblock_primitive_wrapper.v
../../../parts/adc/rtl/soc32e_modular_adc_0.v
../../../parts/spi/rtl/spi.sv
../../../parts/spi/rtl/spiCore.sv
../../../parts/spi/rtl/spiUnit.sv
../../../parts/spi/rtl/spiWithFifos.sv
../../../parts/spi/rtl/spiCoreWithFifos.sv
../../../parts/spi/rtl/spiFifo.sv
../../../parts/spi/rtl/spiFifoMemory.sv
../../../parts/sound/rtl/buffer.sv
../../../parts/sound/rtl/bufferMemory.sv
../../../parts/sound/rtl/pwmUnit.sv
../../../parts/sound/rtl/sigmaDeltaUnit.sv
../../../parts/sound/rtl/sound.sv
../../../parts/sound/rtl/soundCore.sv

../../../parts/interrupt/rtl/interruptController.sv
../../../parts/interrupt/rtl/interruptState.sv

../../BeMicro_soc_interconnect.sv
../../BeMicro_soc.sv
BeMicro_soc_tb.sv

