-suppress 2167

-sv 

+define+DEBUG

../../rtl/globals.sv
../../rtl/boolPkg.sv
../../rtl/execute/alu/rtl/aluPkg.sv
../../rtl/execute/alu/rtl/alu.sv
../../rtl/execute/divider2/rtl/divider2Pkg.sv
../../rtl/execute/divider2/rtl/dividendState.sv
../../rtl/execute/divider2/rtl/divisorState.sv
../../rtl/execute/divider2/rtl/remainderState.sv
../../rtl/execute/divider2/rtl/divider2Controller.sv
../../rtl/execute/divider2/rtl/divider2.sv
../../rtl/execute/multiplier/rtl/dspMultiplier.v
../../rtl/execute/multiplier/rtl/multiplier.sv
../../rtl/execute/shifter/rtl/shifterPkg.sv
../../rtl/execute/shifter/rtl/shift1.sv
../../rtl/execute/shifter/rtl/shift2.sv
../../rtl/execute/shifter/rtl/shift4.sv
../../rtl/execute/shifter/rtl/shift8.sv
../../rtl/execute/shifter/rtl/shift16.sv
../../rtl/execute/shifter/rtl/shifter.sv
../../rtl/regfile/rtl/regfileMemoryBlock2.sv
../../rtl/regfile/rtl/regfileBank.sv
../../rtl/regfile/rtl/regfileInputRegisters.sv
../../rtl/regfile/rtl/regfileLiveValueTable.sv
../../rtl/regfile/rtl/regfile.sv
../../rtl/regfile/rtl/regfileDebug.sv
../../rtl/architecture.sv
../../rtl/debugPkg.sv
../../rtl/address.sv
../../rtl/data.sv
../../rtl/exceptionEncoder.sv
../../rtl/exceptionState.sv
../../rtl/exception.sv
../../rtl/exceptionTrigger.sv
../../rtl/execute.sv
../../rtl/load.sv
../../rtl/programCounter.sv
../../rtl/registerFile.sv
../../rtl/result.sv
../../rtl/system.sv
../../rtl/transaction.sv
../../rtl/controller/controllerPkg.sv
../../rtl/controller/controllerState.sv
../../rtl/controller/addressOutputLogic.sv
../../rtl/controller/conditionCheckLogic.sv
../../rtl/controller/dataOutputLogic.sv
../../rtl/controller/exceptionOutputLogic.sv
../../rtl/controller/exceptionTriggerOutputLogic.sv
../../rtl/controller/executeOutputLogic.sv
../../rtl/controller/instructionDecoder.sv
../../rtl/controller/loadOutputLogic.sv
../../rtl/controller/programCounterOutputLogic.sv
../../rtl/controller/regfileAOutputLogic.sv
../../rtl/controller/regfileBOutputLogic.sv
../../rtl/controller/resultFlagsOutputLogic.sv
../../rtl/controller/resultOutputLogic.sv
../../rtl/controller/stallLogic.sv
../../rtl/controller/systemOutputLogic.sv
../../rtl/controller/transactionOutputLogic.sv
../../rtl/controller/controller.sv
../../rtl/cpu32e2.sv
testRam.sv
disassembler.sv
cpu32e2_model.sv
cpu32e2_tb.sv

